# Cost Constants and Configuration
CLAUDE_INPUT_COST_PER_KTOK = 0.003        # Cost per 1000 input tokens for Claude
CLAUDE_OUTPUT_COST_PER_KTOK = 0.015       # Cost per 1000 output tokens for Claude
GPT_INPUT_COST_PER_KTOK = 0.001
GPT_OUTPUT_COST_PER_KTOK = 0.004
EMBEDDING_COST_PER_KTOK = 0.00001         # Cost for generating embeddings
OBJECT_STORAGE_COST_PER_GB_MONTH = 0.023  # AWS S3 or similar
VECTOR_DB_STORAGE_COST_PER_GB_MONTH = 0   # Pinecone or similar vector DB storage
METADATA_DB_STORAGE_COST_PER_GB_MONTH = 0 # SQLite/PostgreSQL hosting
PROMPT_PARSING_LLM_INPUT_COST_PER_KTOK = GPT_INPUT_COST_PER_KTOK   # Smaller LLM for intent extraction
PROMPT_PARSING_LLM_OUTPUT_COST_PER_KTOK = GPT_OUTPUT_COST_PER_KTOK
VECTOR_SEARCH_COST_PER_1K_OPS = 0    # Vector DB search operations
PROMPT_EMBEDDING_COST_PER_KTOK = 0.00001  # Cost to embed user query
OBJECT_RETRIEVAL_COST_PER_REQUEST = 0  # Download cost from storage
FILE_MONITORING_COST_PER_FILE_MONTH = 0  # VCS diff or file system monitoring
UPDATE_EMBEDDING_COST_PER_KTOK = 0     # Re-embedding changed chunks
DB_UPDATE_COST_PER_OPERATION = 0       # Database write operations
VECTOR_DB_HOSTING_MONTHLY_COST = 0
VECTOR_DB_INFERENCE_COST_PER_KTOK = VECTOR_SEARCH_COST_PER_1K_OPS
OBJECT_STORAGE_COST_PER_REQUEST = OBJECT_RETRIEVAL_COST_PER_REQUEST
STORAGE_COST_PER_GB_MONTH = OBJECT_STORAGE_COST_PER_GB_MONTH

